/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package milkdeez;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manla
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        C2 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        S4 = new javax.swing.JButton();
        S2 = new javax.swing.JButton();
        S1 = new javax.swing.JButton();
        S3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        C = new javax.swing.JComboBox<>();
        S = new javax.swing.JComboBox<>();
        pay = new javax.swing.JButton();
        x = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        amount = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        subtotal = new javax.swing.JTextField();
        discount = new javax.swing.JTextField();
        vat = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        ca = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        change = new javax.swing.JTextField();
        discount3 = new javax.swing.JComboBox<>();
        discount2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        c1q = new javax.swing.JSpinner();
        c2q = new javax.swing.JSpinner();
        c3q = new javax.swing.JSpinner();
        c4q = new javax.swing.JSpinner();
        s1q = new javax.swing.JSpinner();
        s3q = new javax.swing.JSpinner();
        s2q = new javax.swing.JSpinner();
        s4q = new javax.swing.JSpinner();
        pearl = new javax.swing.JToggleButton();
        nata = new javax.swing.JToggleButton();
        CC = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        R2 = new javax.swing.JTextArea();
        P = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1080, 720));

        jTabbedPane1.setBackground(new java.awt.Color(162, 130, 69));

        jPanel2.setBackground(new java.awt.Color(152, 127, 86));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Alpha", 1, 24)); // NOI18N
        jLabel1.setText("Addons");

        jLabel2.setFont(new java.awt.Font("Alpha", 1, 24)); // NOI18N
        jLabel2.setText("Special");

        jLabel3.setFont(new java.awt.Font("Alpha", 1, 24)); // NOI18N
        jLabel3.setText("Classic");

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milkdeez/C2.png"))); // NOI18N
        C2.setPreferredSize(new java.awt.Dimension(105, 105));
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milkdeez/C1.png"))); // NOI18N
        C1.setPreferredSize(new java.awt.Dimension(105, 105));
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milkdeez/C4.png"))); // NOI18N
        C4.setPreferredSize(new java.awt.Dimension(105, 105));
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milkdeez/C3.png"))); // NOI18N
        C3.setPreferredSize(new java.awt.Dimension(105, 105));
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });

        S4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milkdeez/S4.png"))); // NOI18N
        S4.setPreferredSize(new java.awt.Dimension(105, 105));
        S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S4ActionPerformed(evt);
            }
        });

        S2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milkdeez/S2.png"))); // NOI18N
        S2.setPreferredSize(new java.awt.Dimension(105, 105));
        S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S2ActionPerformed(evt);
            }
        });

        S1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milkdeez/S1.png"))); // NOI18N
        S1.setPreferredSize(new java.awt.Dimension(105, 105));
        S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S1ActionPerformed(evt);
            }
        });

        S3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milkdeez/S3.png"))); // NOI18N
        S3.setPreferredSize(new java.awt.Dimension(105, 105));
        S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("ISOCP_IV25", 1, 14)); // NOI18N
        jLabel4.setText("C2-Winter Melon MilkDeez ");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("ISOCP_IV25", 1, 14)); // NOI18N
        jLabel5.setText("C1-Classic MilkDeez ");

        jLabel6.setFont(new java.awt.Font("ISOCP_IV25", 1, 14)); // NOI18N
        jLabel6.setText("C3-Chocolate MilkDeez ");

        jLabel7.setFont(new java.awt.Font("ISOCP_IV25", 1, 14)); // NOI18N
        jLabel7.setText("C4-Vanilla MilkDeez ");

        jLabel8.setFont(new java.awt.Font("ISOCP_IV25", 1, 14)); // NOI18N
        jLabel8.setText("S2-Matcha MilkDeez ");

        jLabel10.setFont(new java.awt.Font("ISOCP_IV25", 1, 14)); // NOI18N
        jLabel10.setText("S1-Cookies and Cream MilkDeez ");

        jLabel11.setFont(new java.awt.Font("ISOCP_IV25", 1, 14)); // NOI18N
        jLabel11.setText("S3-Chocolate Mousse MilkDeez ");

        jLabel9.setFont(new java.awt.Font("ISOCP_IV25", 1, 14)); // NOI18N
        jLabel9.setText("S4-Caramel MilkDeez ");

        C.setBackground(new java.awt.Color(173, 56, 43));
        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Venti", "Trenta" }));
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        S.setBackground(new java.awt.Color(173, 56, 43));
        S.setForeground(new java.awt.Color(255, 255, 255));
        S.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Venti", "Trenta" }));
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });

        pay.setBackground(new java.awt.Color(255, 204, 204));
        pay.setText("PAY");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        x.setBackground(new java.awt.Color(255, 204, 204));
        x.setText("EXIT");
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        amount.setBackground(new java.awt.Color(153, 51, 0));
        amount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Amount", "Quantity", "Addon"
            }
        ));
        amount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amountMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(amount);

        jPanel3.setBackground(new java.awt.Color(187, 68, 68));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });

        vat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatActionPerformed(evt);
            }
        });

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel12.setText("SUBTOTAL");

        jLabel13.setText("DISCOUNT ");

        jLabel14.setText("VAT ");

        jLabel15.setText("TOTAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(169, 93, 81));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setText("CASH");

        ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caActionPerformed(evt);
            }
        });

        jLabel17.setText("CHANGE");

        discount3.setBackground(new java.awt.Color(255, 102, 102));
        discount3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "SENIOR CITIZEN", "PWD" }));

        discount2.setBackground(new java.awt.Color(138, 78, 51));
        discount2.setForeground(new java.awt.Color(255, 255, 255));
        discount2.setText("DISCOUNT");
        discount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discount2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(change))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(discount2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(discount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discount2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        pearl.setBackground(new java.awt.Color(131, 63, 54));
        pearl.setForeground(new java.awt.Color(255, 255, 255));
        pearl.setText("Pearl");
        pearl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pearlActionPerformed(evt);
            }
        });

        nata.setBackground(new java.awt.Color(131, 63, 54));
        nata.setForeground(new java.awt.Color(255, 255, 255));
        nata.setText("Nata");

        CC.setBackground(new java.awt.Color(131, 63, 54));
        CC.setForeground(new java.awt.Color(255, 255, 255));
        CC.setText("Cream Cheese");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pearl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nata))
                            .addComponent(CC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(S4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(544, 544, 544)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(s1q, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(s2q, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(c1q, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(c2q, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(c3q, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(c4q, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(s3q, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(s4q, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 123, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1165, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c1q, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2q, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1q, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s2q, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c3q, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4q, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s3q, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s4q, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pearl)
                                    .addComponent(nata))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CC))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(590, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Menu", jPanel2);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        R2.setColumns(20);
        R2.setRows(5);
        R2.setText("\t\t\n=================================================================");
        jScrollPane2.setViewportView(R2);

        P.setBackground(new java.awt.Color(255, 153, 153));
        P.setText("PRINT");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receipt", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        try {
            R2.print();
        } catch (PrinterException ex) {
            Logger.getLogger(MENU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel)amount.getModel();
        model.setRowCount(0);
        R2.setText("\n=================================================================\n");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void discount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discount2ActionPerformed
        if(discount3.getSelectedItem().equals("none")){
            Cost();
        }
        else
        {
            ItemCostDiscount();
        }
    }//GEN-LAST:event_discount2ActionPerformed

    private void caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void vatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vatActionPerformed

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountActionPerformed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed

    private void amountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_amountMouseClicked

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Print Systems",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
    {
        System.exit(0);}
    }//GEN-LAST:event_xActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
       if(discount.getText().equals("0%"))
       {
              double sum = 0;
    for (int i=0; i < amount.getRowCount(); i++)
    {
    sum = sum + Double.parseDouble(amount.getValueAt(i, 1).toString()); 
    }
    subtotal.setText(Double.toString(sum));
    double cTotal1 = Double.parseDouble(subtotal.getText());
    double cTax = (cTotal1*0.12);
    double dc = 0;
    double tot1 = cTax+cTotal1;
    double tot = cTax+cTotal1;
    double dc2 = 0;
    double ctax2 = 12; 
    double cas = Double.parseDouble(ca.getText());
    
    
    String iTaxTotal = String.format("%.0f%%", ctax2);
    vat.setText(iTaxTotal);
    
    String iSubTotal = String.format("₱%.2f", cTotal1);
    subtotal.setText(iSubTotal);
    
    String Discount = String.format("%.0f%%", dc2);
    discount.setText(Discount);
     
    String jTotal = String.format("₱%.2f",tot1);
    total.setText(jTotal);
    
    String cha = String.format("₱%.2f",cas - tot1);
    change.setText(cha);
       }
       
    if(discount.getText().equals("20%")){
    double sum = 0;
    for (int i=0; i < amount.getRowCount(); i++)
    {
    sum = sum + Double.parseDouble(amount.getValueAt(i, 1).toString()); 
    }
    subtotal.setText(Double.toString(sum));
    double cTotal1 = Double.parseDouble(subtotal.getText());
    double cTax = (cTotal1*0.12);
    double dc = ((cTotal1+cTax)*0.20);
    double tot1 = cTax+cTotal1;
    double tot = cTax+cTotal1-dc;
    double dc2 = 20;
    double ctax2 = 12; 
    double cas = Double.parseDouble(ca.getText());
    
    
    String iTaxTotal = String.format("%.0f%%", ctax2);
    vat.setText(iTaxTotal);
    
    String iSubTotal = String.format("₱%.2f", cTotal1);
    subtotal.setText(iSubTotal);
    
    String Discount = String.format("%.0f%%", dc2);
    discount.setText(Discount);
     
    String jTotal = String.format("₱%.2f",tot);
    total.setText(jTotal);
    
    String cha = String.format("₱%.2f",cas - tot);
    change.setText(cha);
       
       }
    R2.append("\nItem\t\t" + "Amount\t" + "Quantity\t" + "Addon\t" +R2.getText() +"\n=================================================================\n"
            +"\n\t\t\tSubtotal\t" + subtotal.getText() + "\n\t\t\tDiscount\t" + 
            discount.getText() + "\n\t\t\tVAT\t" + vat.getText() + "\n\t\t\tTotal\t" +
            total.getText() + "\n\t\t\tChange\t" + change.getText());
    
    }//GEN-LAST:event_payActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CActionPerformed

    private void S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S3ActionPerformed
        String price = null;
        int tprice = 0;
        int quantity;
        String addon = null;
        quantity =(int) s3q.getValue();
        

        if(C.getSelectedItem().equals("Grande")){
            price = "55";
            int cpg1 = Integer.parseInt(price);
            tprice = cpg1 * quantity;
        }
        if(C.getSelectedItem().equals("Venti")){
            price = "85";
            int cpv1 = Integer.parseInt(price);
           tprice = cpv1 * quantity;
        }
        if(C.getSelectedItem().equals("Trenta")){
            price = "105";
            int cpt1 = Integer.parseInt(price);
           tprice = cpt1 * quantity;
        }
        if (nata.isSelected() == false)
        {
            addon = String.format("none");
        }
        if(pearl.isSelected()){
        pearl.getText();
         addon = pearl.getText();
         tprice = tprice + 10;
        }
        if(nata.isSelected()){
        nata.getText();
         addon = nata.getText();
         tprice = tprice + 10;
        }
        if(CC.isSelected()){
        CC.getText();
         addon = CC.getText();
         tprice = tprice + 15;
        }        
        DefaultTableModel model = (DefaultTableModel)amount.getModel();
        model.addRow(new Object[]{"S3",tprice, quantity, addon});
        R2.append("\nChocolote Mousse MilkDeez\t" + tprice + "\t" + quantity + "\t" + addon + "\n");
    
        Cost();     // TODO add your handling code here:
    }//GEN-LAST:event_S3ActionPerformed

    private void S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S1ActionPerformed
        String price = null;
        int tprice = 0;
        int quantity;
        String addon = null;
        quantity =(int) s1q.getValue();
        

        if(C.getSelectedItem().equals("Grande")){
            price = "55";
            int cpg1 = Integer.parseInt(price);
            tprice = cpg1 * quantity;
        }
        if(C.getSelectedItem().equals("Venti")){
            price = "85";
            int cpv1 = Integer.parseInt(price);
           tprice = cpv1 * quantity;
        }
        if(C.getSelectedItem().equals("Trenta")){
            price = "105";
            int cpt1 = Integer.parseInt(price);
           tprice = cpt1 * quantity;
        }
        if (nata.isSelected() == false)
        {
            addon = String.format("none");
        }
        if(pearl.isSelected()){
        pearl.getText();
         addon = pearl.getText();
         tprice = tprice + 10;
        }
        if(nata.isSelected()){
        nata.getText();
         addon = nata.getText();
         tprice = tprice + 10;
        }
        if(CC.isSelected()){
        CC.getText();
         addon = CC.getText();
         tprice = tprice + 15;
        }        
        DefaultTableModel model = (DefaultTableModel)amount.getModel();
        model.addRow(new Object[]{"S1",tprice, quantity, addon});
        R2.append("\nCookiesnCream MilkDeez\t" + tprice + "\t" + quantity + "\t" + addon + "\n");
    
        Cost();        // TODO add your handling code here:
    }//GEN-LAST:event_S1ActionPerformed

    private void S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S2ActionPerformed
        String price = null;
        int tprice = 0;
        int quantity;
        String addon= null;
        quantity =(int) s2q.getValue();
        

        if(C.getSelectedItem().equals("Grande")){
            price = "55";
            int cpg1 = Integer.parseInt(price);
            tprice = cpg1 * quantity;
        }
        if(C.getSelectedItem().equals("Venti")){
            price = "85";
            int cpv1 = Integer.parseInt(price);
           tprice = cpv1 * quantity;
        }
        if(C.getSelectedItem().equals("Trenta")){
            price = "105";
            int cpt1 = Integer.parseInt(price);
           tprice = cpt1 * quantity;
        }
        if (nata.isSelected() == false)
        {
            addon = String.format("none");
        }
        if(pearl.isSelected()){
        pearl.getText();
         addon = pearl.getText();
         tprice = tprice + 10;
        }
        if(nata.isSelected()){
        nata.getText();
         addon = nata.getText();
         tprice = tprice + 10;
        }
        if(CC.isSelected()){
        CC.getText();
         addon = CC.getText();
         tprice = tprice + 15;
        }        
        DefaultTableModel model = (DefaultTableModel)amount.getModel();
        model.addRow(new Object[]{"S2",tprice, quantity, addon});
        R2.append("\nMatcha MilkDeez\t" + tprice + "\t" + quantity + "\t" + addon + "\n");
    
        Cost();       // TODO add your handling code here:
    }//GEN-LAST:event_S2ActionPerformed

    private void S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S4ActionPerformed
        String price = null;
        int tprice = 0;
        int quantity;
        String addon = null;
        quantity =(int) s4q.getValue();
        

        if(C.getSelectedItem().equals("Grande")){
            price = "55";
            int cpg1 = Integer.parseInt(price);
            tprice = cpg1 * quantity;
        }
        if(C.getSelectedItem().equals("Venti")){
            price = "85";
            int cpv1 = Integer.parseInt(price);
           tprice = cpv1 * quantity;
        }
        if(C.getSelectedItem().equals("Trenta")){
            price = "105";
            int cpt1 = Integer.parseInt(price);
           tprice = cpt1 * quantity;
        }
        if (nata.isSelected() == false)
        {
            addon = String.format("none");
        }
        if(pearl.isSelected()){
        pearl.getText();
         addon = pearl.getText();
         tprice = tprice + 10;
        }
        if(nata.isSelected()){
        nata.getText();
         addon = nata.getText();
         tprice = tprice + 10;
        }
        if(CC.isSelected()){
        CC.getText();
         addon = CC.getText();
         tprice = tprice + 15;
        }
        DefaultTableModel model = (DefaultTableModel)amount.getModel();
        model.addRow(new Object[]{"S4",tprice, quantity, addon});
        R2.append("\nCaramel MilkDeez\t" + tprice + "\t" + quantity + "\t" + addon + "\n");
    
        Cost();       // TODO add your handling code here:
    }//GEN-LAST:event_S4ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        String price = null;
        int tprice = 0;
        String addon = null;
        int quantity;
        quantity =(int) c3q.getValue();
        

        if(C.getSelectedItem().equals("Grande")){
            price = "50";
            int cpg1 = Integer.parseInt(price);
            tprice = cpg1 * quantity;
        }
        if(C.getSelectedItem().equals("Venti")){
            price = "75";
            int cpv1 = Integer.parseInt(price);
           tprice = cpv1 * quantity;
        }
        if(C.getSelectedItem().equals("Trenta")){
            price = "95";
            int cpt1 = Integer.parseInt(price);
           tprice = cpt1 * quantity;
        }
        if (nata.isSelected() == false)
        {
            addon = String.format("none");
        }
                if(pearl.isSelected()){
        pearl.getText();
         addon = pearl.getText();
         tprice = tprice + 10;
        }
        if(nata.isSelected()){
        nata.getText();
         addon = nata.getText();
         tprice = tprice + 10;
        }
        if(CC.isSelected()){
        CC.getText();
         addon = CC.getText();
         tprice = tprice + 15;
        }
        DefaultTableModel model = (DefaultTableModel)amount.getModel();
        model.addRow(new Object[]{"C3",tprice, quantity, addon});
        R2.append("\nChocolaate MilkDeez\t" + tprice + "\t" + quantity + "\t" + addon + "\n");
    
        Cost();
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        String price = null;
        int tprice = 0;
        int quantity;
        String addon =null;
        quantity =(int) c4q.getValue();
        

        if(C.getSelectedItem().equals("Grande")){
            price = "50";
            int cpg1 = Integer.parseInt(price);
            tprice = cpg1 * quantity;
        }
        if(C.getSelectedItem().equals("Venti")){
            price = "75";
            int cpv1 = Integer.parseInt(price);
           tprice = cpv1 * quantity;
        }
        if(C.getSelectedItem().equals("Trenta")){
            price = "95";
            int cpt1 = Integer.parseInt(price);
           tprice = cpt1 * quantity;
        }
        if (nata.isSelected() == false)
        {
            addon = String.format("none");
        }
        if(pearl.isSelected()){
        pearl.getText();
         addon = pearl.getText();
         tprice = tprice + 10;
        }
        if(nata.isSelected()){
        nata.getText();
         addon = nata.getText();
         tprice = tprice + 10;
        }
        if(CC.isSelected()){
        CC.getText();
         addon = CC.getText();
         tprice = tprice + 15;
        }        
        DefaultTableModel model = (DefaultTableModel)amount.getModel();
        model.addRow(new Object[]{"C4",tprice, quantity, addon});
        R2.append("\nVanilla MilkDeez\t" + tprice + "\t" + quantity + "\t" + addon + "\n");
    
        Cost();       // TODO add your handling code here:
    }//GEN-LAST:event_C4ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        String price;
        int tprice = 0;
        int quantity;
        String addon = null;
        quantity =(int) c1q.getValue();
        

        if(C.getSelectedItem().equals("Grande")){
            price = "50";
            int cpg1 = Integer.parseInt(price);
            tprice = cpg1 * quantity;
        }
        if(C.getSelectedItem().equals("Venti")){
            price = "75";
            int cpv1 = Integer.parseInt(price);
           tprice = cpv1 * quantity;
        }
        if(C.getSelectedItem().equals("Trenta")){
            price = "95";
            int cpt1 = Integer.parseInt(price);
           tprice = cpt1 * quantity;
        }
        
        if (nata.isSelected() == false)
        {
            addon = String.format("none");
        }
        if(pearl.isSelected()){
        pearl.getText();
         addon = pearl.getText();
         tprice = tprice + 10;
        } 
        if(nata.isSelected()){
        nata.getText();
         addon = nata.getText();
         tprice = tprice + 10;
        }
        if(CC.isSelected()){
        CC.getText();
         addon = CC.getText();
         tprice = tprice + 15;
        }

        DefaultTableModel model = (DefaultTableModel)amount.getModel();
        model.addRow(new Object[]{"C1",tprice, quantity , addon});
        
        R2.append("\nClassic MilkDeez\t" + tprice + "\t" + quantity + "\t" + addon + "\n");
    
        Cost();
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        String price = null;
        int tprice = 0;
        int quantity;
        String addon = null;
        quantity =(int) c2q.getValue();
        

        if(C.getSelectedItem().equals("Grande")){
            price = "50";
            int cpg1 = Integer.parseInt(price);
            tprice = cpg1 * quantity;
        }
        if(C.getSelectedItem().equals("Venti")){
            price = "75";
            int cpv1 = Integer.parseInt(price);
           tprice = cpv1 * quantity;
        }
        if(C.getSelectedItem().equals("Trenta")){
            price = "95";
            int cpt1 = Integer.parseInt(price);
           tprice = cpt1 * quantity;
        }
                if (nata.isSelected() == false)
        {
            addon = String.format("none");
        }
                if(pearl.isSelected()){
        pearl.getText();
         addon = pearl.getText();
         tprice = tprice + 10;
        }
        if(nata.isSelected()){
        nata.getText();
         addon = nata.getText();
         tprice = tprice + 10;
        }
        if(CC.isSelected()){
        CC.getText();
         addon = CC.getText();
         tprice = tprice + 15;
        }
        DefaultTableModel model = (DefaultTableModel)amount.getModel();
        model.addRow(new Object[]{"C2",tprice, quantity, addon});
        R2.append("\nWinter Melon MilkDeez\t" + tprice + "\t" + quantity + "\t" + addon + "\n");
    
        Cost();
    }//GEN-LAST:event_C2ActionPerformed

    private void pearlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pearlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pearlActionPerformed
   
    
    public void Cost()
    {
   double sum = 0;
    for (int i=0; i < amount.getRowCount(); i++)
    {
    sum = sum + Double.parseDouble(amount.getValueAt(i, 1).toString()); 
    }
    subtotal.setText(Double.toString(sum));
    double cTotal1 = Double.parseDouble(subtotal.getText());
    double cTax = (cTotal1*0.12);
    double dc = 0;
    double tot1 = cTax+cTotal1;
    double tot = cTax+cTotal1;
    double dc2 = 0;
    double ctax2 = 12; 
    
    
    String iTaxTotal = String.format("%.0f%%", ctax2);
    vat.setText(iTaxTotal);
    
    String iSubTotal = String.format("₱%.2f", cTotal1);
    subtotal.setText(iSubTotal);
    
    String Discount = String.format("%.0f%%", dc2);
    discount.setText(Discount);
     
    String jTotal = String.format("₱%.2f",tot1);
    total.setText(jTotal);
    }
 public void ItemCostDiscount()
    {
   double sum = 0;
    for (int i=0; i < amount.getRowCount(); i++)
    {
    sum = sum + Double.parseDouble(amount.getValueAt(i, 1).toString()); 
    }
    subtotal.setText(Double.toString(sum));
    double cTotal1 = Double.parseDouble(subtotal.getText());
    double cTax = (cTotal1*0.12);
    double dc = ((cTotal1+cTax)*0.20);
    double tot1 = cTax+cTotal1;
    double tot = cTax+cTotal1-dc;
    double dc2 = 20;
    double ctax2 = 12; 
    
    
    String iTaxTotal = String.format("%.0f%%", ctax2);
    vat.setText(iTaxTotal);
    
    String iSubTotal = String.format("₱%.2f", cTotal1);
    subtotal.setText(iSubTotal);
    
    String Discount = String.format("%.0f%%", dc2);
    discount.setText(Discount);
     
    String jTotal = String.format("₱%.2f",tot);
    total.setText(jTotal);
    }

    private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> C;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JToggleButton CC;
    private javax.swing.JButton P;
    private javax.swing.JTextArea R2;
    private javax.swing.JComboBox<String> S;
    private javax.swing.JButton S1;
    private javax.swing.JButton S2;
    private javax.swing.JButton S3;
    private javax.swing.JButton S4;
    private javax.swing.JTable amount;
    private javax.swing.JSpinner c1q;
    private javax.swing.JSpinner c2q;
    private javax.swing.JSpinner c3q;
    private javax.swing.JSpinner c4q;
    private javax.swing.JTextField ca;
    private javax.swing.JTextField change;
    private javax.swing.JTextField discount;
    private javax.swing.JButton discount2;
    private javax.swing.JComboBox<String> discount3;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton nata;
    private javax.swing.JButton pay;
    private javax.swing.JToggleButton pearl;
    private javax.swing.JSpinner s1q;
    private javax.swing.JSpinner s2q;
    private javax.swing.JSpinner s3q;
    private javax.swing.JSpinner s4q;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField total;
    private javax.swing.JTextField vat;
    private javax.swing.JButton x;
    // End of variables declaration//GEN-END:variables

    private void If(boolean equals) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
